### ISSUE TITLE
[Proposal] Migrate from ethers@5 to viem?

### ISSUE THREAD

**Issue by Songkeys** [Crossbell-Box/crossbell.js#10]
The `wagmi-dev` team is currently developing an alternative to `ethers` called [`viem`](https://github.com/wagmi-dev/viem). The maintainer is also discussing the possibility of [integrating `viem` into future releases of `wagmi`](https://github.com/wagmi-dev/wagmi/discussions/1782#discussioncomment-5292169).

In my opinion,

1. `ethers@6` is relatively new and has yet to undergo extensive development and maintenance.
2. `wagmi` is the most popular library for dapps today.
3. `viem` [appears to be a promising solution in many aspects](https://viem.sh/docs/introduction.html).

I am considering transitioning the entire underlying stack to `Viem`. However, this process may take some time as it could potentially disrupt many elements in our system (e.g. the contract SDK, the indexer, and the sites). For now, I would like to wait and see how `wagmi`'s migration goes. It may be the future, but we don't stand to gain anything from it more than `ethers@5`. Therefore, I am putting this on hold with a "?" and in the v1 milestone in anticipation of breaking changes.

Please let me know your thoughts.

**Comment by jxom** [comment]
I am happy to answer any questions ☺️

**Comment by Songkeys** [comment]
@jxom Thank you! I had a chance to take a look at viem yesterday, and I must say it looks great! However, I'm concerned if it can handle the backend work our project requires, such as contract interaction and event listening, as it appears to be browser-oriented. I'm not sure if it will be a good fit.

What's more, we're using `typechain` to generate the ABI typings for `ethers` in our project. It looks like `viem` is using a similar technique to `wagmi`, which uses TypeScript inference. Is there something like the `@wagmi/cli` that can generate further types and functions, or do you think the current setup is sufficient?

Another question is: what is the anticipated status of `viem`? When will it reach maturity and become battle-tested? When will there be integration with `wagmi`?

---

I also tried to send a transaction but failed because of an error:

```ts
import { Wallet } from "ethers"; // v5
import { createWalletClient, createPublicClient, http } from "viem";
import { getAccount } from "viem/ethers";

const walletClient = createWalletClient({
	transport: http("https://rpc.crossbell.io"),
});
const publicClient = createPublicClient({
	transport: http("https://rpc.crossbell.io"),
});
const wallet = new Wallet(privateKey);
const account = getAccount(wallet);

const { request } = await publicClient.simulateContract({
	account,
	address: "0xa6f969045641Cf486a747A2688F3a5A6d43cd0D8",
	abi: [
		{
			inputs: [
				{
					components: [
						{
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							internalType: "string",
							name: "handle",
							type: "string",
						},
						{
							internalType: "string",
							name: "uri",
							type: "string",
						},
						{
							internalType: "address",
							name: "linkModule",
							type: "address",
						},
						{
							internalType: "bytes",
							name: "linkModuleInitData",
							type: "bytes",
						},
					],
					internalType: "struct DataTypes.CreateCharacterData",
					name: "vars",
					type: "tuple",
				},
			],
			name: "createCharacter",
			outputs: [
				{
					internalType: "uint256",
					name: "characterId",
					type: "uint256",
				},
			],
			stateMutability: "nonpayable",
			type: "function",
		},
	],
	functionName: "createCharacter",
	args: [
		{
			to: address,
			handle: genRandomHandle(),
			uri: metadataUri,
			linkModule: "0x0000000000000000000000000000000000000000",
			linkModuleInitData: "0x0000000000000000000000000000000000000000",
		},
	],
});
const hash = await walletClient.writeContract(request);

// util
function genRandomHandle() {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
	let handle = "";
	for (let i = 0; i < 10; i++) {
		handle += chars.charAt(Math.floor(Math.random() * chars.length));
	}
	return "a-random-handle-" + handle;
}
```

The error was emitted from the ether.js signTransaction, I think.

```
/Users/songkeys/GitHub/playground/node_modules/viem/dist/chunk-XMKUHSC7.js:3321
  return new TransactionExecutionError(cause, {
         ^

TransactionExecutionError: An error occurred.

Request Arguments:
  from:  0x00000081d48bA02DAa6C13D55C2916aD0570B652
  to:    0xa6f969045641Cf486a747A2688F3a5A6d43cd0D8
  data:  0xcd69fe61000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000081d48ba02daa6c13d55c2916ad0570b65200000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000001a612d72616e646f6d2d68616e646c652d797265746a3374323538000000000000000000000000000000000000000000000000000000000000000000000000003c697066733a2f2f516d544d4436734c41374d346965674b446862644d50425a34484c6935666a57323777324a3136677163354362372f312e6a736f6e0000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000000

Details: invalid object key - account (argument="transaction:account", value="[object Object]", code=INVALID_ARGUMENT, version=properties/5.7.0)
Version: viem@0.1.19
    at getTransactionError (/Users/songkeys/GitHub/playground/node_modules/viem/dist/chunk-XMKUHSC7.js:3321:10)
    at sendTransaction (/Users/songkeys/GitHub/playground/node_modules/viem/dist/chunk-XMKUHSC7.js:5090:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async writeContract (/Users/songkeys/GitHub/playground/node_modules/viem/dist/chunk-XMKUHSC7.js:5224:17)
```

I haven't taken a deep look though. Let me know if I did anything wrong or you need more info.
