### ISSUE TITLE
[Doc] A Developer-Friendly Documentation Website

### ISSUE THREAD

**Issue by Songkeys** [Crossbell-Box/crossbell.js#12]
The title conveys the topic.

The current documentation is API-focused. We need an improved documentation website to help more developers to build the ecosystem.

## Framework

Let us discuss the documentation framework first. I am currently considering [nextra](https://github.com/shuding/nextra) and [vitepress](https://github.com/vuejs/vitepress). I am unsure, but nextra seems better. What do you think?

## Doc structure

The following aspects come to mind:

-  Getting Started (of course, every doc requires this)
-  Guides
  - Characters
  - Notes
  - Links
  - Operators
  - Tips
  - ...
  - Newbie Villa
  - Op Sign
  - ...
-  Framework-specific guides (#11 )
-  More...

Let me know if you would like to assist.

**Comment by Songkeys** [comment]
It's now on docs.crossbell.io

**Comment by sxzz** [comment]
So can we close this now?

**Comment by Songkeys** [comment]
Sure
