### ISSUE TITLE
Adjust Fetch Polyfill

### ISSUE THREAD

**Issue by sxzz** [Crossbell-Box/crossbell.js#18]
Fetch API now is already supported by modern browsers and Node.js >= 18. 

For browsers, we can completely remove the polyfills.

For the node version (cjs and esm), we can replace `fetch-undici` (which is deprecated) with `undici`. They're the same but `undici` is the latest one. Also, we can also completely remove polyfills after [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/) (Which is the EOL of Node 16).

/cc @Songkeys

**Comment by Songkeys** [comment]
fetch-undici is not deprecated yet. It's the isomorphic exports of fetch. We can directly use undici but have to bundle it correctly for browser.

I agree we can remove it, actually even before v16 EOL. Let's do it in the next version (v1).

**Comment by sxzz** [comment]
Oh, there are actually two similar libraries `undici-fetch` and `fetch-undici`. I was wrong about these two.

**Comment by sxzz** [comment]
Is there a reason to do it in the next major version? Since for 0.x.x, we can release breaking changes in a minor version.

**Comment by Songkeys** [comment]
We can but we don't have to since it doesn't improve what matters a lot. I'm thinking about starting v1 very soon. 0.19.x might be the last major version. But yes, we can.
