### ISSUE TITLE
[Proposal] Support SDK to interact with customized rpc and chainId

### ISSUE THREAD

**Issue by saltad-dev** [Crossbell-Box/crossbell.js#80]
Currently, the SDK is using the default config exported from viem. It's easy and clear for production but I believe it is not friendly for development. 

I built a crossbell-env project: https://github.com/saltad-dev/crossbell-env. It is to simulate crossbell env locally to help develop easier. Honestly I am thinking is there a way to use it along with crossbell SDK? e.g. when I develop a project, I could write some code like
```
import { crossbell } from "crossbell/network";
crossbell.id = 31337;
crossbell.rpcUrls = {
    default: {
      http: ['http://127.0.0.1:8545'],
    },
  },
```

So that we could use SDK to interact with local env. I believe that would help all development based on crossbell.js more easier to debug or test.

**Comment by Songkeys** [comment]
Hi, I've replied to you in discord:

When creating contract, you can set the `options.chain` arg:

```ts
import { crossebll } from "crossbell"
const contract = createContract({
  chain: {
    id: ...
  }
})
```

https://github.com/Crossbell-Box/crossbell.js/blob/e203d15a05f3d92bece22d1ce0e49cde1edd7113/src/contract/subcontracts/base.ts#L116

**Comment by saltad-dev** [comment]
Thanks for your reply. It works pretty cool.
