### ISSUE TITLE
[Proposal] A Mint/Link Module Store & A Universal Metadata

### ISSUE THREAD

**Issue by Songkeys** [Crossbell-Box/crossbell.js#9]
## Background

We are about to launch the functionality of mint/link modules. The first module will be the [`ApproveMintModule`](https://crossbell-box.github.io/Crossbell-Contracts/contracts/modules/mint/ApprovalMintModule.sol/contract.ApprovalMintModule.html), which only allows a restricted group of whitelisted addresses to mint a note.

To use it in `crossbell.js`, pass in the `mintModule` option. Taking the `ApproveMintModule` as an example:

```ts
await contract.postNote(characterId, metadataOrUri, {
  mintModule: {
    address: "0x8d040b35cEad83782c62845BEbE026504B73b509", // the address of ApproveMintModule
    data: [
      {
        type: 'address[]',
        value: [
          0x8ba1f109551bd432803012645ac136ddd64dba72,
          0x8ba1f109551bd432803012645ac136ddd64dba73,
        ], // the whitelisted group of addresses
      },
      {
        type: 'uint256',
        value: 1024, // the number of nfts available to mint
      },
    ],
  },
})
```

This structure poses a challenge for frontend apps to adapt to every module. We need to make it runtime dynamic to achieve higher maintenance.

### Dev Store

The proposed solution is a module store, with data stored in the [Crossbell-Box/Crossbell-Contracts](https://github.com/Crossbell-Box/Crossbell-Contracts) GitHub Repository. Initially, only a json file is needed for the store (might not be the best solution but work). It goes like:

```jsonc
// modules.json
[
  {
    "id": "ApproveMintModule",
    "type": "mint",
    "address": "0x8d040b35cEad83782c62845BEbE026504B73b509",
    "name": "Approve",
    "description": "Only allow a restricted group of addresses to mint the note, with limited number of mints",
    "icon": "https://example.com/module.webp",
    "authorCharacterId": 30,
    "initDataStructure": [
      {
        "label": "Allowed Addresses",
        "description": "The whitelisted group of addresses to mint this note",
        "type": "address[]"
      },
      {
        "label": "Available amount",
        "description": "The number of nfts available to mint",
        "type": "uint256"
      }
    ]
    // more attributes see below
  },
  {
    "name": "Another Module",
    // ... the second module
  },
  // ... more modules
]
```

The universal metadata structure of a module is:

```ts
interface Module {
  /* Global unique id */
  id: string
  /* Type of the module */
  type: "mint" | "link"
  /* The contract address of this module */
  address: string
  /* Display name */
  name: string
  /* Display Description */
  description: string
  /* Module icon, an image url, in 256*256px */
  icon?: string
  /* The character id of the author */
  authorCharacterId?: number
  /* Structure of Init data, a form to fill out in frontend */
  initDataStructure: {
    /* Label of this field */
    label: string
    /* Data type of this field. E.g. "address[]", "uint256", ... see https://docs.soliditylang.org/en/latest/abi-spec.html#types */
    type: string
    /* Description of this field */
    description: string
    /* Whether or not required, default: true */
    required?: boolean
  }[]
  /* Published date string */
  createdAt?: string
}
```

### SDK API

To interact with the module store:

```tsx
// browse the store
const modules = await contract.getModules()

// assume we get a module
const module = modules[0]
// render the form to let user fill in
module.dataStructure.map(field => <div>...</div>)
// submit as we did in the beginning of this proposal
await contract.postNote(characterId, metadataOrUri, {
  mintModule: {
    address: module.address,
    data: module.initDataStructure.map((field, i) => ({
      type: field.type,
      value: userFormValues[i].value, // get the value from whatever store in frontend
    }))
  },
})
```

**Comment by Atlasoin** [comment]
A universal metadata structure for different modules is really a good idea. But for SDK API part, it seems not concise enough.

If we are interacting with the module store, why not use SDK API as something like:
```
// submit as we did in the beginning of this proposal
await contract.postNote(characterId, metadataOrUri, {
  mintModule: {
    address: module.APPROVE_MINT_MODULE,
    data: {
        addresses: ["0x1111", "0x2222"],
        approvedAmount: 1,
    }
  },
})

// Maybe if we want to be more developer-friendly, we could have stricter type check for the variable ``data``
   ...
    data: {
        addresses: ["0x1111", "0x2222"],
        approvedAmount: 1,
    } as APPROVE_MINT_MODULE_INIT_DATA
    ...
```
Since we have specified the exact module(approve mint module in this case) to interact, the params will be decoded in the determined way. Developer could pass the prams they want directly.

**Comment by Songkeys** [comment]
@Atlasoin  Indeed, using argument names and typings would be more intuitive. However, in most cases, modules are agnostic to the compile-time. The user selects the module they wish to use and passes in the corresponding arguments at runtime. In this case, the typings and specific argument names and typings of the data are not necessary.

**Comment by Atlasoin** [comment]
Sure, it's not necessary, just a way to help developers make less mistakes.

As for the syntax this way:
```
     ...
    data: module.dataStructure.map((field, i) => ({
      type: field.type, // Here developer has to use "field.type"
      value: userFormValues[i].value, // get the value from whatever store in frontend
    }))
```
I feel the main problem is that, when the module is specified, the corresponding types are specified as well. Developer has no freedom to modify that type. Only ``field type`` is the correct usage. If so, why does SDK set type in dataStructure as variable?

**Comment by Songkeys** [comment]
```diff
    data: module.dataStructure.map((field, i) => ({
-     type: field.type, // Here developer has to use "field.type"
      value: userFormValues[i].value, // get the value from whatever store in frontend
    }))
```

Yes, this line is not necessary. However, if not, the internal function must infer the type from the module mapping with a helper function, `getTypesFromModule(name)`. This function can be implemented in two ways:

1. Network fetch the modules.json metadata and find the types. (Con: network request delay).
2. Cache the modules.json from the previous request (`contract.getModules()`); if no previous request, request once. Cache invalidation must also be considered. Then, use the cached metadata to find the types. (Con: extra and complex logic, and potential unwanted caching behavior).

Given that the developer must obtain the data structure from modules.json anyway, writing one extra line does not add any cost. As stated, in most cases, it should be written dynamically (e.g., coded in `map`), not in a specific way (e.g., coded in object literal `[{ type: "uint256", value: 123 }]`). So, TypeScript definition also doesn't help a lot here. I do considered some type restricted solution like:

```ts
await contract.postNote(characterId, metadataOrUri, {
  mintModule: new ApproveMintModule([address], 1024)
})
```

If we consider the TypeScript definition, this SDK must be updated whenever a new module is released, which is an issue this proposal seeks to address. In other words, we are seeking a general data structure that is independent of the module and typings at compile-time, but still works at runtime.

**Comment by Songkeys** [comment]
update

Now I've implemented the API like this:

```ts
await contract.postNote(characterId, metadataOrUri, {
  mintModule: {
    address: module.APPROVE_MINT_MODULE,
    data: [["0x1111", "0x2222"], 1],
  },
})
```
